// src/app/layout.js - CORRECTED VERSION

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
        The className that was here has been removed. 
        This is the most important change.
      */}
      <body>{children}</body>
    </html>
  );
}